# Italian-English Vocabulary Dictionary
# Generated from vocab_list.txt

vocab_dict = {
    'buongiorno': 'good morning',
    'zucchine': 'zucchini',
    'fontane': 'fountain',
    'insalata': 'salad',
    'Il conto, per favore!': 'The bill, please!',
    'piazza': 'square',
    'coltello': 'knife',
    'pera': 'pear',
    'vino bianco': 'white wine',
    'carciofo': 'artichoke',
    'pomodori': 'tomato',
    'vicolo': 'alley',
    'melanzane': 'eggplant',
    'pepe': 'pepper',
    'cameriere': 'waiter',
    'senta, scusi': 'listen, excuse me',
    'cipolla': 'onion',
    'buonanotte': 'good night',
    'cornetto al cioccolato': 'chocolate croissant',
    'torre': 'tower',
    'Scusi, dov\' e la fermata della metropolitan/del tram/del bus?': 'Excuse me, where is the subway/tram/bus stop?',
    'pane': 'bread',
    'patate': 'potato',
    'mura romane': 'roman walls/murals',
    'cinema': 'movie theater/cinema',
    'arrivederla': 'goodbye (formal)',
    'caffelatte': 'coffee with milk',
    'tramezzino': 'sandwich/club sandwich',
    'antipasto': 'appetizer',
    'Quanto pago?': 'How much do I pay?',
    'sale': 'salt',
    'vino rosso': 'red wine',
    'basilico': 'basil',
    'il menù': 'menu',
    'panino': 'sandwich/panini',
    'limone': 'lemon',
    'taxi': 'taxi',
    'pasta': 'pasta',
    'bar': 'coffee shop',
    'saluti': 'greetings',
    'mercato': 'market',
    'città': 'city',
    'ristorante': 'restaurant',
    'Io sono ___': 'I am ___ (name/nationality)',
    'Io sono di ___': 'I am from ___',
    'Che (cosa) significa ___?': 'What\'s the meaning of ___?',
    'Come se dice "___" in italiano?': 'How d you say "___" in Italian?',
    'Come si scri ve ___?': 'How do you write ___?',
    'Può ripetere, per favore?': 'Can you repeat, please?',
    'Non lo so': 'I don\'t know',
    'Mastered (25)': 'You\'ve been getting these terms right!',
    'Select these 25': 'caffè',
    'coffee': 'palazzo',
    'palace/building': 'Vorrei un cappuccino, per favore!',
    'I would like a cappuccino please!': 'mele',
    'apples': 'salve',
    'hello (formal)': 'museo',
    'museum': 'carne',
    'meat': 'chiesa',
    'church': 'dolce',
    'dessert': 'arrivederci',
    'goodbye (informal)': 'teatro',
    'theater': 'latte macchiato',
    'milk with a few drops of coffee': 'contorno',
    'side dish': 'bicchiere',
    'drinking glass': 'cornetto con la crema',
    'cream-filled croissant': 'ciao',
    'hello/goodbye (informal)': 'arancia',
    'orange': 'birra',
    'beer': 'verdura',
    'vegetable': 'tavolo',
    'table': 'frutta',
    'fruit': 'cassa',
    'cash register': 'Quant\' e?',
    'How much is it?': 'uva',
    'grape': 'tè',


}
